### ISSUE TITLE
json serializer doesn't seem to be working.

### ISSUE THREAD

**Issue by konsumer** [ericelliott/express-error-handler#14]
I add this before other routes:

```js
app.use(errorHandler({
  serializer: err => {
    return err
  }
}))
```

I still get errors like this (plaintext):

```
Error: Authentication failed. Password incorrect.<br> &nbsp; &nbsp;at User.js:29:35
```

when I call next with `new Error('Authentication failed. Password incorrect.')`

**Comment by konsumer** [comment]
If I put it at the end of the middleware, I get a DOS in 3 consecutive calls.

**Comment by ericelliott** [comment]
Error handler middleware needs to go after your routes.

**Comment by konsumer** [comment]
As I said, if it's  at the end, my server crashes after 3 consecutive calls, but the error messages look correct. I may be doing something funny in an error. I will try to figure it out.

**Comment by ericelliott** [comment]
Server shut down is intentional. It's a good response to an unhandled 500 error. See [this answer on StackOverflow](http://stackoverflow.com/questions/15684130/express-js-error-handling#answer-19420310) and ["Let it Crash"](http://chimera.labs.oreilly.com/books/1234000000262/ch05.html#let-it-crash) from ["Programming JavaScript Applications"](http://pjabook.com).

**Comment by konsumer** [comment]
Well, in my case I am using 500 status to mean something different. No prob. I am just sending this, now:

```js
res.status(500).send({message: 'Descriptive error here.'})
```

**Comment by ericelliott** [comment]
HTTP errors have specific, well-known meanings. 500 errors are server errors that the user can't do anything about. Typically this happens in response to an unhandled exception in the server code -- in other words, a bug.

What are you using it to indicate?

**Comment by konsumer** [comment]
Let's just agree to disagree on semantic meaning of HTTP status-codes. There are lots of non-fatal 500s on a great number of REST services in the world, many of which are written by smarter people than you or I. From w3c, it simply means this:

```
The server encountered an unexpected condition which prevented it from fulfilling the request.
```

I use it as a general error that means this:

```
It's not a problem with auth, or something missing, or bad input, just something bad happened, and it may be telling you too much to say exactly what it was.
```

This is pretty typical usage.

I thought it would be helpful to to you to report that my server crashes after 3 consecutive 500 statuses when I use your error-handler, which is totally not expected or normal behavior for express. If you expect this, and like your error-handler doing this, more power to ya!

In my situation, I want to pass all errors with mongo or authentication or whatever up to a central error-handler, where I can decide if the user should see the text of the error (if it's running in dev-mode) or just a generic "there was an error" sort of message. In my central handler, I can decide what should be done about it, and what status code to send.

I ended up just not using this lib and making my own error-handler. It works great!

**Comment by ericelliott** [comment]
Cheers. =)
