### ISSUE TITLE
Server unable to close properly after listening crashes

### ISSUE THREAD

**Issue by gzurbach** [ericelliott/express-error-handler#6]
Hi!

First of all, I wanted to thank you for that great little library that I have been using for quite a bit now. It works great :)

Today, I started to use [node-domain-middleware](https://github.com/brianc/node-domain-middleware) in addition to your handler to catch errors happening in asynchronous calls.

Quote from node-domain-middleware's README:

> If the domain emits an error event, node-domain-middleware will call next(err) with the error event from the domain. This allows existing express specific error handling middleware to function as if the error was handled by your application code.

That sounds perfect except that when the error is passed to your handler, nodejs is already "crashed" and has stopped listening. Therefore, I'm getting the following error:

```
Error: Not running
    at Server.close (net.js:1236:11)
    at close (C:\projects\server\node_modules\express-error-handler\error-handler.js:56:16)
    at errorHandler (C:\projects\server\node_modules\express-error-handler\error-handler.js:303:5)
```

I investigated the issue and there are a couple ways to handle that:
1. Put a `try/catch` around the `server.close()` and simply exit the process in the `catch`
2. Test whether `server._handle` is not null before closing (hack explained [here](https://stackoverflow.com/questions/8750698/closing-a-server-after-listening-crashes-with-not-running-exception))

I will be happy to submit a pull request if you accept contributions.

Thanks!

**Comment by gzurbach** [comment]
FYI: the bug in the server.close() method was fixed in Node 0.12. It does not throw exceptions anymore: https://github.com/joyent/node/commit/f1dc55d7018e2669550a8be2c5b6c091da616483
I think it might be a good thing to remove the try/catch at some point since it's not necessary.

**Comment by gzurbach** [comment]
After investigating all possible cases for several hours I think the most robust version of that function would be the following (comments removed for readability):

```
close = function close(o, exit) {
  if (o.server && typeof o.server.close === 'function') {
    try {
      o.server.close(function (err) {
        if (!err) {
          // everything went well
          process.exit(o.exitStatus);
        }
      });
    }
    catch(ex) { // keep the try/catch for node 0.10 }
  }

  // in case of error, we must wait a couple seconds so most connections
  // still have time to close
  exit(o);
}
```

This code should cover most cases:
 - if using node 0.10, the close() method will throw. We just swallow the error and let the exit() method wait 3 seconds before killing the process.
 - if using node 0.12, the close() method will pass and error object in the callback. We just ignore the error and let the exit() method wait 3 seconds before killing the process.
 - if the close() method never fires its callback, we let the exit() method wait 3 seconds before killing the process.

What do you think? I tested all possible scenarios and all types of errors. Note that this issue (server.close() blowing up) only occurs if you use domains to handle uncaught exceptions and pass them to the express error handler.

I can send you a PR if that works for you.

**Comment by ericelliott** [comment]
Please do. I'll need to test. Did you test this with io.js?

**Comment by gzurbach** [comment]
I have not used io.js yet. Node covered all my needs so far. I can take a look this week if you want.
